spring:
  application:
    name: upload-svc
  rabbitmq:
    host: 18.139.222.137
    port: 5672
    username: admin
    password: adminlgsp@123
    profile:
      exchange: event.exchange1
      queue: event.queue1
      routingkey: event.routingkey1
    CV:
      exchange: cv.exchange
      queue: cv.queue
      routingkey: cv.routingkey
    email:
      exchange: email.exchange
      queue: email.queue
      routingkey: email.routingkey
  redis:
    host: 18.139.222.137
    port: 6379
    password: 'hhhhhhhhhhsdvnsldvmsdlvmsdlkvmsdv'
    database: 6
    lettuce:
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
        max-wait: -1ms
      shutdown-timeout: 200ms
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    mongodb:
      host: 18.139.222.137
      port: 27017
      database: 'resume'
      username: 'resume'
      password: 'abc123resume'
    elasticsearch:

elasticsearch:
  clustername: elasticsearch
  host: localhost
  port: 9300

server:
  port: ${ACCOUNT_SVC_PORT:30005}
  http2:
    enabled: true
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:30000/eureka/}

logging:
  config: config/log4j2.xml

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

zuul:
  host:
    socket-timeout-millis: 10000
    connect-timeout-millis: 10000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000

application:
  version: ${VERSION:1.0}

pdf:
  domain: http://file-rs.edsolabs.com/
  localpath: fileupload/
  serverpath: /usr/share/nginx/file-rs/

email:
  sender:
    host: smtp.gmail.com
    port: 587
    username: resume-noti@edsolabs.com
    password: UZ8mJEZma5fwnM4n
  transport:
    protocol: smtp
  smtp:
    auth: true
    starttls:
      enable: true
  debug: false
  from:
    address: resume-noti@edsolabs.com

refresh-token:
  url: 'https://login.microsoftonline.com/common/oauth2/v2.0/token'
  client_id: '0f4945ae-656d-4dc3-a1ed-b104e41610fc'
  scope: 'user.read'
  refresh_token: 'M.R3_BAY.-CZUf8ZamSjQF89JrrqmuKKS49XBh*1qznW9xW4d7G!HYElikdjHQWmk5M0x7uyhEXjP3qVND!50ccL1!vb3gSyzZV66ZhLFWpepSfhSJqYNcHsB1oTXm43*zsQW*nQxvzjZvUdO*ArQS2BbfKKXaXnQEV!QAub3j4v4bGkx7QPdQLhR*BEqkubMC8EHXzMBK9mqUvoYvnzqxwAHibxDClaVE7RWa5gcUhQBMU4bY6M5K4y5SQRt55ldHYWejS!4ZQfwMiQqDlPWm2m19HyW!2hHbnT9A8vS0xqsg!CMOqVkwLDtMyukxH*IUZodn9TOBaA$$'
  redirect_uri: 'http://localhost'
  grant_type: 'refresh_token'
  client_secret: 'ogU7Q~AZ81lAtVSUCqYne4ggOEw6ph64yVOMA'
send-outlook:
  url: 'https://graph.microsoft.com/v1.0/me/events'