spring:
  application:
    name: upload-svc
  rabbitmq:
    host: 18.139.222.137
    port: 5672
    username: admin
    password: rabb@t@7911
    exchange: event.exchange
    queue: event.queue
    routingkey: event.routingkey
  redis:
    host: '103.152.165.53'
    port: 9981
    password: 'hhhhhhhhhhsdvnsldvmsdlvmsdlkvmsdv'
    lettuce:
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
        max-wait: -1ms
      shutdown-timeout: 200ms
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    mongodb:
      host: 103.152.165.53
      port: 27017
      database: 'resume'
      username: 'resume'
      password: 'abc123resume'
    elasticsearch:

elasticsearch:
  clustername: elasticsearch
  host: localhost
  port: 9300

server:
  port: ${ACCOUNT_SVC_PORT:30005}
  http2:
    enabled: true
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:30000/eureka/}

logging:
  config: config/log4j2.xml

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

zuul:
  host:
    socket-timeout-millis: 10000
    connect-timeout-millis: 10000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000

application:
  version: ${VERSION:1.0}

pdf:
  domain: http://file-rs.edsolabs.com/
  localpath: fileupload/
  serverpath: /usr/share/nginx/file-rs/
